development:
  adapter: mysql2
  encoding: utf8
  password: password
  host: localhost
  database: tournaments_development
  username: tournaments
  pool: 5

test:
  adapter: mysql2
  encoding: utf8
  password: password
  host: localhost
  database: tournaments_test
  username: tournaments
  pool: 5

