development:
  adapter: postgresql
  encoding: unicode
  password: password
  host: localhost
  database: tournaments_development
  username: postgres
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  password: password
  host: localhost
  database: tournaments_test
  username: postgres
  pool: 5

